// Generated file. Do not edit.
// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PROJECT_NAME = 'facebook';
  static const String PROJECT_VERSION = '1.0.0+1';
  static const String FACEBOOK = 'assets/images/Facebook.png';
  static const String MESSENGER = 'assets/images/Messenger.png';
  static const String NOTIFICATION = 'assets/images/Notification.png';
  static const String PHOTOS = 'assets/images/Photos.png';
  static const String PLUS = 'assets/images/Plus.png';
  static const String PROFILE = 'assets/images/Profile.png';
  static const String SEARCH = 'assets/images/Search.png';
  static const String STORE = 'assets/images/Store.png';
  static const String STORY_IMAGE_1 = 'assets/images/Story_Image_1.png';
  static const String BRANDING = 'assets/images/branding.png';
  static const String FACEBOOKBRANDING = 'assets/images/facebookBranding.png';
  static const String FACEBOOKLOGO = 'assets/images/facebookLogo.png';
  static const String HOME = 'assets/images/home.png';
  static const String LOGO = 'assets/images/logo.png';
  static const String REELS = 'assets/images/reels.png';
  static const String USER_IMAGE = 'assets/images/user_image.png';
}
