// Generated file. Do not edit.
// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PROJECT_NAME = 'facebook';
  static const String PROJECT_VERSION = '1.0.0+1';
  static const String FACEBOOK = 'assets/Facebook.png';
  static const String MESSENGER = 'assets/Messenger.png';
  static const String NOTIFICATION = 'assets/Notification.png';
  static const String PHOTOS = 'assets/Photos.png';
  static const String PLUS = 'assets/Plus.png';
  static const String PROFILE = 'assets/Profile.png';
  static const String SEARCH = 'assets/Search.png';
  static const String STORE = 'assets/Store.png';
  static const String STORY_IMAGE_1 = 'assets/Story_Image_1.png';
  static const String BRANDING = 'assets/branding.png';
  static const String HOME = 'assets/home.png';
  static const String REELS = 'assets/reels.png';
  static const String USER_IMAGE = 'assets/user_image.png';
}
